export const SET_INGREDIENT_COUNT_BUN:'SET_INGREDIENT_COUNT_BUN' = 'SET_INGREDIENT_COUNT_BUN';
export const ADD_INGREDIENT_COUNT:'ADD_INGREDIENT_COUNT' = 'ADD_INGREDIENT_COUNT';
export const REMOVE_INGREDIENT_COUNT:'REMOVE_INGREDIENT_COUNT' = 'REMOVE_INGREDIENT_COUNT';